---
name: build

on:
  workflow_dispatch:

  workflow_call:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: ''

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: actions/checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          token: ${{ github.token }}
          fetch-depth: 0

      - name: actions/setup-go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491  # v5.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: go version
        run: |
          go version
          go env

      - name: go mod tidy
        run: |
          go mod tidy

      - name: go clean --cache
        run: |
          go clean --cache

      - name: pre-build
        id: prebuild
        run: |
          echo "pre-building"
          goversion=$(go version)
          echo "goversion=${goversion}"
          echo "::set-output name=goversion::${goversion}"
          appversion=$(cat .version)
          echo "appversion=${appversion}"
          echo "::set-output name=appversion::${appversion}"
          buildtime=$(date -u "+%Y-%m-%dT%TZ")
          echo "buildtime=${buildtime}"
          echo "::set-output name=buildtime::${buildtime}"

      - name: go build
        run: |
          go env
          mkdir dist
          go build -x -v -ldflags="-s -w \
            -X 'internal/version.AppVersion=${{ steps.prebuild.outputs.appversion }}' \
            -X 'internal/version.Branch=${{ env.target_ref }}' \
            -X 'internal/version.BuildTime=${{ steps.prebuild.outputs.buildtime }}' \
            -X 'internal/version.Commit=${{ github.sha }}' \
            -X 'internal/version.GoVersion=${{ steps.prebuild.outputs.goversion }}'" \
            -o dist/my-go-template cmd/my-go-template/main.go
