---
name: CI

on:
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan workflow call:
  workflow_call:
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]
  # Scan changed files in PRs (diff-aware scanning):
  pull_request:
    branches: ["master", "main"]

# Don't grant any access by default
permissions: {}

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: ''

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        go-version: ['stable']  # only use ONE version of go here or the upload-artifact will fail
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: actions/checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b  # v4.1.5
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          token: ${{ github.token }}
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your
          #                             personal access token.
          fetch-depth: 0

      - name: Load super-linter configuration
        run: |
          cat ".github/super-linter.env" >> "${GITHUB_ENV}"

      - name: super-linter/super-linter
        uses: super-linter/super-linter@56576d491db07c7236b445ab09991ca49d12b0c6  # v6.5.0
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: actions/setup-go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7  # v5.0.1
        with:
          go-version: ${{ matrix.go-version }}

      - name: go version
        run: |
          go version
          go env

      - name: go mod tidy
        run: |
          go mod tidy

      - name: go clean --cache
        run: |
          go clean --cache

      - name: golangci/golangci-lint-action
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64  # v6.0.1
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the
          # latest version. When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash
          # of a commit.
          version: latest

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          #
          # Note: By default, the `.golangci.yml` file should be at the root of the repository.
          # The location of the configuration file can be changed by using `--config=`
          # args: --timeout=30m --config=/my/path/.golangci.yml --issues-exit-code=0
          args: --verbose
            --tests=true
            --timeout=1m
            --config=.github/linters/.golangci.yml
            --issues-exit-code=1

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true, then all caching functionality will be completely disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true, then the action won't cache or restore ~/go/pkg.
          # skip-pkg-cache: true
          skip-pkg-cache: true

          # Optional: if set to true, then the action won't cache or restore ~/.cache/go-build.
          # skip-build-cache: true

          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          # install-mode: "goinstall"

      - name: go test
        run: |
          go env
          go test -v -race -coverprofile=coverage.gcov -covermode=atomic ./...
          go test -v -coverprofile=coverage.gcov -covermode=count ./...
          go tool cover -func=coverage.gcov -o=coverage.out

      - name: jandelgado/gcov2lcov-action
        uses: jandelgado/gcov2lcov-action@c680c0f7c7442485f1749eb2a13e54a686e76eb5  # v1.0.9
        with:
          infile: coverage.gcov
          outfile: coverage.lcov

      - name: VeryGoodOpenSource/very_good_coverage
        uses: VeryGoodOpenSource/very_good_coverage@c953fca3e24a915e111cc6f55f03f756dcb3964c  # v3.0.0
        with:
          path: coverage.lcov
          min_coverage: 40

      - name: pre-build
        id: prebuild
        run: |
          echo "pre-building"
          goversion=$(go version)
          echo "goversion=${goversion}"
          echo "goversion=${goversion}" >> "$GITHUB_OUTPUT"
          appversion=$(git describe --tags)
          echo "appversion=${appversion}"
          echo "appversion=${appversion}" >> "$GITHUB_OUTPUT"
          buildtime=$(date -u "+%Y-%m-%dT%TZ")
          echo "buildtime=${buildtime}"
          echo "buildtime=${buildtime}" >> "$GITHUB_OUTPUT"

      - name: go build
        run: |
          go env
          mkdir dist
          APP=my-go-template
          go build -x -v -ldflags="-s -w \
            -X 'internal/version.AppVersion=${{ steps.prebuild.outputs.appversion }}' \
            -X 'internal/version.Branch=${{ env.target_ref }}' \
            -X 'internal/version.BuildTime=${{ steps.prebuild.outputs.buildtime }}' \
            -X 'internal/version.Commit=${{ github.sha }}' \
            -X 'internal/version.GoVersion=${{ steps.prebuild.outputs.goversion }}'" \
            -o dist/${APP} cmd/${APP}/main.go

      # Upload generated artifacts for historical reference
      - name: actions/upload-artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808  # v4.3.3
        with:
          name: test-reports
          path: ./coverage.*
          retention-days: 180

      - name: Show Artifact ID
        run: |
          echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
