---
name: coverage

on:
  workflow_dispatch:

  workflow_call:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: ''

jobs:
  coverage:
    name: Coverage
    strategy:
      matrix:
        go-version: ['stable']  # only use ONE version of go here or the upload-artifact will fail
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: actions/checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          token: ${{ github.token }}
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your
          #                             personal access token.
          fetch-depth: 0

      - name: actions/setup-go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491  # v5.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: go version
        run: |
          go version
          go env

      - name: go mod tidy
        run: |
          go mod tidy

      - name: go clean --cache
        run: |
          go clean --cache

      - name: go test -race -coverprofile=coverage.gcov -covermode=atomic ./...
        run: |
          go env
          go test -race -coverprofile=coverage.gcov -covermode=atomic ./...

      - name: jandelgado/gcov2lcov-action
        uses: jandelgado/gcov2lcov-action@c680c0f7c7442485f1749eb2a13e54a686e76eb5  # v1.0.9
        with:
          infile: coverage.gcov
          outfile: coverage.lcov

      - name: VeryGoodOpenSource/very_good_coverage
        uses: VeryGoodOpenSource/very_good_coverage@3b475421464c564c0714d92ce02742bd81fa9eda  # v2.2.0
        with:
          path: coverage.lcov
          min_coverage: 65

      # Upload generated artifacts for historical reference
      - name: actions/upload-artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8  # v4.3.0
        with:
          name: test-reports
          path: ./coverage.*
          retention-days: 180
