name: Pull Request Checks

on:
  pull_request:

env:
  target_ref: ${{ github.head_ref || github.ref_name }}

jobs:
  call-linter:
    name: Go Linter
    uses: ./.github/workflows/linter.yaml

  call-tests:
    name: Tests
    uses: ./.github/workflows/tests.yaml

  call-build:
    name: Go Build
    uses: ./.github/workflows/build.yaml
