---
name: report

on:
  workflow_dispatch:

  workflow_call:

  push:

  pull_request:

env:
  target_ref: ${{ github.head_ref || github.ref_name }}

jobs:
  report:
    name: Report
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: report-step
        id: report-id
        run: |
          echo "reporting:"
          echo "github.event_name: ${{ github.event_name }}"
          echo "runner.os: ${{ runner.os }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.repository: ${{ github.repository }}"
          echo "job.status: ${{ job.status }}"
          echo "env.target_ref: ${{ env.target_ref }}"
          echo "github.workspace: ${{ github.workspace }}"
          ls -als ${{ github.workspace }}
          echo "EOR"
