---
name: tests

on:
  workflow_dispatch:

  workflow_call:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  target_ref: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: ''

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: actions/checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.target_ref }}
          token: ${{ github.token }}
          fetch-depth: 0

      - name: actions/setup-go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491  # v5.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: go version
        run: go version

      - name: go mod tidy
        run: go mod tidy

      - name: go clean
        run: go clean --cache

      - name: go test
        run: |
          go env
          go test -v -race -coverprofile=coverprofile.gcov -covermode=atomic ./...
          go test -v -coverprofile=coverprofile.gcov -covermode=count ./...
          go tool cover -func=coverprofile.gcov -o=coverage.out
